// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUuCmRMAzwt8-EYYcZsaMJUqZzF0FDeA0',
    appId: '1:263384268159:web:19fae87573a2e9a223ee4a',
    messagingSenderId: '263384268159',
    projectId: 'nexfit-gym',
    authDomain: 'nexfit-gym.firebaseapp.com',
    storageBucket: 'nexfit-gym.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhHcI2tYet3m8k-iWLBTWgXL0wM_AlUo',
    appId: '1:263384268159:android:bcb294b3f7bb61b023ee4a',
    messagingSenderId: '263384268159',
    projectId: 'nexfit-gym',
    storageBucket: 'nexfit-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKu3_Z4Cgh29IZzBIo-RJNtq44g5Cgqlc',
    appId: '1:263384268159:ios:0d71077b838033cf23ee4a',
    messagingSenderId: '263384268159',
    projectId: 'nexfit-gym',
    storageBucket: 'nexfit-gym.firebasestorage.app',
    iosBundleId: 'cl.nexfit.gym',
  );
}
